kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  log-format: '$remote_addr - $remote_user [$time_iso8601] "$request" ($host) $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'